// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZkQnJ-8AtbM9sYkIwLqAFDDNO67cQ_xo',
    appId: '1:697151334771:web:b904e269f96ee6755cbd06',
    messagingSenderId: '697151334771',
    projectId: 'servicetracker-technicians',
    authDomain: 'servicetracker-technicians.firebaseapp.com',
    storageBucket: 'servicetracker-technicians.appspot.com',
    measurementId: 'G-Q21MQMRLF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYXtCPuF_Phnv-j7N7yHebMezE_d_oB0E',
    appId: '1:697151334771:android:55c6096d12d6c7d15cbd06',
    messagingSenderId: '697151334771',
    projectId: 'servicetracker-technicians',
    storageBucket: 'servicetracker-technicians.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGhxpYq4TwufnjlWiXRIkinrfjhWvYRkw',
    appId: '1:697151334771:ios:692ea38cd0e89ce15cbd06',
    messagingSenderId: '697151334771',
    projectId: 'servicetracker-technicians',
    storageBucket: 'servicetracker-technicians.appspot.com',
    iosClientId: '697151334771-s5plj7028c314jr6nht0qvh5ih442nhm.apps.googleusercontent.com',
    iosBundleId: 'com.v1ack.serviceTracker',
  );
}
